# Schema for the configuration files of the Tester module.

tester.settings:
  type: config_object
  label: 'Testing'
  mapping:
    clear_results:
      type: boolean
      label: 'Clear results after each complete test suite run'
    phpunit:
      type: mapping
      label: 'PHPUnit execution options'
      mapping:
        config_yaml:
          type: string
          label: 'YAML compliant text with all options'
